name: AWS Test

on: [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  aws-test:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::905418428715:role/fossa-branch
      - name: Step name
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            FOSSA_API_KEY, fossa
      - run: |
          set -ex
          echo $FOSSA_API_KEY
          aws sts get-caller-identity
