name: Test Testing Test

on:
  pull_request_target:
    branches:
      - main

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  security-license-scan:
    uses: finn-tbd-test-org/.github/.github/workflows/test.yml@main
    secrets: inherit